- hosts: mac-compute
  vars:
    storage_port: 6000
    ssl_storage_port: 6001
    native_transport_port: 7042
    rpc_port: 7160
    seeds: 127.0.0.1
    cluster_name: SparkCluster
    jmx_port: 6199
    home: /Users/chbatey

  roles:
    - cassandra
    - spark
