- hosts: mac-compute
  vars:
    storage_port: 6000
    ssl_storage_port: 6001
    native_transport_port: 7042
    rpc_port: 7160
    seeds: 10.65.84.81, 10.65.84.105
    cluster_name: SparkCluster
    jmx_port: 6199
    home: /Users/cirrus

  roles:
    - spark
    - cassandra
