---
- hosts: dev
  remote_user: chbatey
  vars:
    - home_dir: /Users/chbatey/
    - applications:
       - ant
       - virtualbox
       - caffeine
       - google-drive
       - hipchat
       - java
       - firefox
       - colloquy
       - iterm2
       - skype
       - vagrant
       - intellij-idea-ce
       - evernote
       - vlc
       - sublime-text
       - google-chrome
  roles:
    - repos
    - { role: shell, tags: ["shell"] }

  tasks:
    - name: install brew packages
      homebrew: update_homebrew=yes name={{ item }}
      with_items:
        - htop
        - wget
        - scala
        - sbt
        - gpg
        - tig
        - python
        - tmux
        - zsh
        - zsh-completions
        - golang
        - tree
      tags:
        - brew

    # - name: install brew cask
    #   command: brew install caskroom/cask/brew-cask

    - name: install functions etc to home directory
      copy: src={{ item }} dest={{ home_dir }}
      with_items:
        - functions.sh
        - .gitconfig
        - .profile
      tags:
        - shell      

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install apps with brew-cask   
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results|map(attribute='stdout')
