---
- hosts: dev
  remote_user: chbatey
  vars:
    - home_dir: /Users/chbatey/
    - applications:
       - virtualbox
       - caffeine
       - google-drive
       - hipchat
       - java
       - firefox
       - colloquy
       - iterm2
       - skype
       - vagrant
       - intellij-idea-ce
       - evernote
       - vlc
       - sublime-text
       - google-chrome
    - dev_ansible_home: dev/ansible/ 
    - dev_scassandra_home: dev/os/scassandra/ 
    - dev_light_practice: dev/yo/lightpractice/ 
    - repos:
       - repo: git@github.com:chbatey/ansible-home-office.git
         location: "{{ home_dir }}{{ dev_ansible_home }}ansible-home-office"
       - repo: git@github.com:scassandra/scassandra-it-java-driver-2.git
         location: "{{ home_dir }}{{ dev_scassandra_home }}scassandra-it-java-driver-2"
       - repo: git@github.com:scassandra/scassandra-it-java-driver-1.git
         location: "{{ home_dir }}{{ dev_scassandra_home }}scassandra-it-java-driver-1"
       - repo: git@github.com:scassandra/scassandra-server.git
         location: "{{ home_dir }}{{ dev_scassandra_home }}scassandra-server"
       - repo: git@github.com:chbatey/scassandra-java-client.git
         location: "{{ home_dir }}{{ dev_scassandra_home }}scassandra-java-client"
       - repo: git@github.com:balooo/lightpractice.git
         location: "{{ home_dir }}{{ dev_light_practice }}lightpractice"

  tasks:
    - name: install brew packages
      homebrew: update_homebrew=yes name={{ item }}
      with_items:
        - htop
        - wget
        - scala
        - sbt
        - gpg
        - tig
        - python

    - name: install brew cask
      command: brew install caskroom/cask/brew-cask

    - name: install functions etc to home directory
      copy: src={{ item }} dest={{ home_dir }}
      with_items:
        - functions.sh
        - .git-completion.bash
        - .gitconfig
      tags:
        - bash

    - name: source functions in bash home
      lineinfile: dest=~/.bash_profile line="source ~/functions.sh" create=yes
      tags:
        - bash
    
    - name: source git completions
      lineinfile: dest=~/.bash_profile line="source ~/.git-completion.bash" create=yes
      tags:
        - bash

    - name: Create dev directories
      file: path={{ home_dir }}{{ item }} state=directory
      with_items:
        - "{{ dev_ansible_home }}"
        - dev/learn/scala/
        - "{{ dev_light_practice }}"
      tags:
        - repos

    - name: Checkout repos
      git: repo={{ item.repo }} dest={{ item.location }}
      with_items: repos
      tags: 
        - repos

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install apps with brew-cask   
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results|map(attribute='stdout')


# todo: vagrant, intellij, java8
