---
dirs:
  dev_ansible_home: dev/ansible/
  dev_scassandra_home: dev/os/scassandra/
  dev_kafka_unit: dev/os/kafka/
  dev_light_practice: dev/yo/lightpractice/
  dev_datastax: dev/datastax/
  dev_learn: dev/learn/
  dev_learn_memcaches: dev/learn/memcaches/
  dev_examples: dev/examples/
repos:
  - repo: git@github.com:chbatey/scassandra-example-java.git
    location: "{{ home_dir }}{{ dirs.dev_scassandra_home }}scassandra-example"
  - repo: git@github.com:scassandra/scassandra-server.git
    location: "{{ home_dir }}{{ dirs.dev_scassandra_home }}scassandra-server"
  - repo: git@github.com:chbatey/cassandra-sstable-obfuscator.git
    location: "{{ home_dir }}{{ dirs.dev_datastax }}cassandra-sstable-obfuscator"
  - repo: git@github.com:chbatey/cassandra-customer-events-dropwizard.git
    location: "{{ home_dir }}{{ dirs.dev_datastax }}cassandra-customer-events-dropwizard"
  - repo: git@github.com:chbatey/cassandra-customer-events.git
    location: "{{ home_dir }}{{ dirs.dev_datastax }}cassandra-customer-events"
  - repo: git@github.com:chbatey/vagrant-cassandra-spark.git
    location: "{{ home_dir }}{{ dirs.dev_datastax }}vagrant-cassandra-spark"
  - repo: git@github.com:chbatey/memcache-akka-scala.git
    location: "{{ home_dir }}{{ dirs.dev_learn_memcaches }}memcache-akka-scala"
  - repo: git@github.com:chbatey/memcache-netty.git
    location: "{{ home_dir }}{{ dirs.dev_learn_memcaches }}memcache-netty"
  - repo: git@github.com:chbatey/kafka-unit.git
    location: "{{ home_dir }}{{ dirs.dev_kafka_unit }}kafka-unit"
  - repo: git@github.com:chbatey/spring-cloud-example.git
    location: "{{ home_dir }}{{ dirs.dev_examples }}spring-cloud-example"
  - repo: git@github.com:chbatey/dropwizard-hystrix.git
    location: "{{ home_dir }}{{ dirs.dev_examples }}dropwizard-hystrix"
  - repo: git@github.com:chbatey/vagrant-wiremock-saboteur.git
    location: "{{ home_dir }}{{ dirs.dev_examples }}vagrant-wiremock-saboteur"
  - repo: git@github.com:chbatey/cassandra-anti-patterns.git
    location: "{{ home_dir }}{{ dirs.dev_datastax }}cassandra-anti-patterns"
  - repo: git@github.com:chbatey/killrauction.git
    location: "{{ home_dir }}{{ dirs.dev_datastax }}killrauction"

